In [1]:
import pandas as pd

In [10]:
df=pd.read_csv("s1.csv")

In [9]:
df.head()

,customer_id,created_date,canceled_date,subscription_cost,subscription_interval,was_subscription_paid
0,154536156,2022-09-01,NaN,39,month,Yes
1,149713408,2022-09-01,2022-09-02,39,month,No
2,153756284,2022-09-01,2022-09-02,39,month,No
3,121253113,2022-09-01,2022-09-23,39,month,Yes
4,154467210,2022-09-01,2023-06-29,39,month,Yes

In [11]:
df.tail()

,customer_id,created_date,canceled_date,subscription_cost,subscription_interval,was_subscription_paid
3064,221145374,2023-09-07,NaN,39,month,Yes
3065,221130434,2023-09-07,NaN,39,month,Yes
3066,221189604,2023-09-08,NaN,39,month,Yes
3067,215174643,2023-09-08,NaN,39,month,Yes
3068,188354637,2023-09-08,NaN,39,month,Yes

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3069 entries, 0 to 3068
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            3069 non-null   int64
 1   created_date           3069 non-null   object
 2   canceled_date          2004 non-null   object
 3   subscription_cost      3069 non-null   int64
 4   subscription_interval  3069 non-null   object
 5   was_subscription_paid  3069 non-null   object
dtypes: int64(2), object(4)
memory usage: 144.0+ KB

In [14]:
df.dtypes

customer_id               int64
created_date             object
canceled_date            object
subscription_cost         int64
subscription_interval    object
was_subscription_paid    object
dtype: object

In [15]:
df.describe()

        customer_id  subscription_cost
count  3.069000e+03             3069.0
mean   1.827553e+08               39.0
std    3.007863e+07                0.0
min    1.113945e+08               39.0
25%    1.559263e+08               39.0
50%    1.841436e+08               39.0
75%    2.142482e+08               39.0
max    2.211896e+08               39.0

In [23]:
#filter
filter_rows = df[df["was_subscription_paid"].str.lower() == "yes"]
filter_rows

,customer_id,created_date,canceled_date,subscription_cost,subscription_interval,was_subscription_paid
0,154536156,2022-09-01,NaN,39,month,Yes
3,121253113,2022-09-01,2022-09-23,39,month,Yes
4,154467210,2022-09-01,2023-06-29,39,month,Yes
5,154510811,2022-09-01,2023-05-08,39,month,Yes
6,154494346,2022-09-01,2022-11-26,39,month,Yes
...,...,...,...,...,...,...
3064,221145374,2023-09-07,NaN,39,month,Yes
3065,221130434,2023-09-07,NaN,39,month,Yes
3066,221189604,2023-09-08,NaN,39,month,Yes
3067,215174643,2023-09-08,NaN,39,month,Yes
3068,188354637,2023-09-08,NaN,39,month,Yes

In [27]:
#selecting cols
n=df["subscription_interval"]
s=df[["subscription_interval","was_subscription_paid","subscription_cost"]]
s

     subscription_interval was_subscription_paid  subscription_cost
0                    month                   Yes                 39
1                    month                    No                 39
2                    month                    No                 39
3                    month                   Yes                 39
4                    month                   Yes                 39
...                    ...                   ...                ...
3064                 month                   Yes                 39
3065                 month                   Yes                 39
3066                 month                   Yes                 39
3067                 month                   Yes                 39
3068                 month                   Yes                 39

[3069 rows x 3 columns]

In [29]:
#slicing
ss=df.iloc[0:5]
ss

,customer_id,created_date,canceled_date,subscription_cost,subscription_interval,was_subscription_paid
0,154536156,2022-09-01,NaN,39,month,Yes
1,149713408,2022-09-01,2022-09-02,39,month,No
2,153756284,2022-09-01,2022-09-02,39,month,No
3,121253113,2022-09-01,2022-09-23,39,month,Yes
4,154467210,2022-09-01,2023-06-29,39,month,Yes

In [30]:
#combined filtering + col selection
frow = df[df["was_subscription_paid"].str.lower() == "yes"][["subscription_interval","was_subscription_paid","subscription_cost"]]
frow

     subscription_interval was_subscription_paid  subscription_cost
0                    month                   Yes                 39
3                    month                   Yes                 39
4                    month                   Yes                 39
5                    month                   Yes                 39
6                    month                   Yes                 39
...                    ...                   ...                ...
3064                 month                   Yes                 39
3065                 month                   Yes                 39
3066                 month                   Yes                 39
3067                 month                   Yes                 39
3068                 month                   Yes                 39

[2936 rows x 3 columns]

In [31]:
frow.to_csv("filtered_row.csv",index=False)

In [32]:
pd.read_csv("filtered_row.csv")

     subscription_interval was_subscription_paid  subscription_cost
0                    month                   Yes                 39
1                    month                   Yes                 39
2                    month                   Yes                 39
3                    month                   Yes                 39
4                    month                   Yes                 39
...                    ...                   ...                ...
2931                 month                   Yes                 39
2932                 month                   Yes                 39
2933                 month                   Yes                 39
2934                 month                   Yes                 39
2935                 month                   Yes                 39

[2936 rows x 3 columns]